#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : totem
Version  : 3.34.0
Release  : 17
URL      : https://download.gnome.org/sources/totem/3.34/totem-3.34.0.tar.xz
Source0  : https://download.gnome.org/sources/totem/3.34/totem-3.34.0.tar.xz
Summary  : Movie player for the GNOME desktop based on GStreamer
Group    : Development/Tools
License  : GPL-2.0
Requires: totem-bin = %{version}-%{release}
Requires: totem-data = %{version}-%{release}
Requires: totem-lib = %{version}-%{release}
Requires: totem-libexec = %{version}-%{release}
Requires: totem-license = %{version}-%{release}
Requires: totem-locales = %{version}-%{release}
Requires: totem-man = %{version}-%{release}
Requires: grilo
Requires: grilo-plugins
BuildRequires : buildreq-cmake
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : docbook-xml
BuildRequires : glibc-bin
BuildRequires : gobject-introspection-dev
BuildRequires : grilo
BuildRequires : grilo-dev
BuildRequires : grilo-plugins
BuildRequires : gst-plugins-good
BuildRequires : intltool
BuildRequires : itstool
BuildRequires : libpeas-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(clutter-1.0)
BuildRequires : pkgconfig(clutter-gst-3.0)
BuildRequires : pkgconfig(clutter-gtk-1.0)
BuildRequires : pkgconfig(gdk-3.0)
BuildRequires : pkgconfig(gdk-pixbuf-2.0)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gnome-desktop-3.0)
BuildRequires : pkgconfig(gsettings-desktop-schemas)
BuildRequires : pkgconfig(gstreamer-1.0)
BuildRequires : pkgconfig(gstreamer-plugins-base-1.0)
BuildRequires : pkgconfig(gstreamer-tag-1.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libnautilus-extension)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(pygobject-3.0)
BuildRequires : pylint
BuildRequires : totem-pl-parser-dev

%description
=====
libgd
=====
Introduction
============
libgd is a library used by various GNOME 3 styled applications.
However, it is not a typical library, since it doesn't guarantee
API/ABI stability, nor does it has official releases tarballs. Only
the files actually used by your project will be shipped with its
tarball. Only the necessary dependencies will be checked during
configure time and used at runtime.

%package bin
Summary: bin components for the totem package.
Group: Binaries
Requires: totem-data = %{version}-%{release}
Requires: totem-libexec = %{version}-%{release}
Requires: totem-license = %{version}-%{release}

%description bin
bin components for the totem package.


%package data
Summary: data components for the totem package.
Group: Data

%description data
data components for the totem package.


%package dev
Summary: dev components for the totem package.
Group: Development
Requires: totem-lib = %{version}-%{release}
Requires: totem-bin = %{version}-%{release}
Requires: totem-data = %{version}-%{release}
Provides: totem-devel = %{version}-%{release}
Requires: totem = %{version}-%{release}
Requires: totem = %{version}-%{release}

%description dev
dev components for the totem package.


%package doc
Summary: doc components for the totem package.
Group: Documentation
Requires: totem-man = %{version}-%{release}

%description doc
doc components for the totem package.


%package lib
Summary: lib components for the totem package.
Group: Libraries
Requires: totem-data = %{version}-%{release}
Requires: totem-libexec = %{version}-%{release}
Requires: totem-license = %{version}-%{release}

%description lib
lib components for the totem package.


%package libexec
Summary: libexec components for the totem package.
Group: Default
Requires: totem-license = %{version}-%{release}

%description libexec
libexec components for the totem package.


%package license
Summary: license components for the totem package.
Group: Default

%description license
license components for the totem package.


%package locales
Summary: locales components for the totem package.
Group: Default

%description locales
locales components for the totem package.


%package man
Summary: man components for the totem package.
Group: Default

%description man
man components for the totem package.


%prep
%setup -q -n totem-3.34.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568046757
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain -Denable-vala=no  builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/totem
cp COPYING %{buildroot}/usr/share/package-licenses/totem/COPYING
cp license_change %{buildroot}/usr/share/package-licenses/totem/license_change
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang totem

%files
%defattr(-,root,root,-)
/usr/lib64/totem/plugins/apple-trailers/apple-trailers.plugin
/usr/lib64/totem/plugins/autoload-subtitles/autoload-subtitles.plugin
/usr/lib64/totem/plugins/dbus/dbusservice.plugin
/usr/lib64/totem/plugins/dbus/dbusservice.py
/usr/lib64/totem/plugins/im-status/totem-im-status.plugin
/usr/lib64/totem/plugins/media-player-keys/media-player-keys.plugin
/usr/lib64/totem/plugins/open-directory/open-directory.plugin
/usr/lib64/totem/plugins/opensubtitles/hash.py
/usr/lib64/totem/plugins/opensubtitles/opensubtitles.plugin
/usr/lib64/totem/plugins/opensubtitles/opensubtitles.py
/usr/lib64/totem/plugins/opensubtitles/opensubtitles.ui
/usr/lib64/totem/plugins/properties/movie-properties.plugin
/usr/lib64/totem/plugins/pythonconsole/console.py
/usr/lib64/totem/plugins/pythonconsole/pythonconsole.plugin
/usr/lib64/totem/plugins/pythonconsole/pythonconsole.py
/usr/lib64/totem/plugins/recent/recent.plugin
/usr/lib64/totem/plugins/rotation/rotation.plugin
/usr/lib64/totem/plugins/save-file/save-file.plugin
/usr/lib64/totem/plugins/screensaver/screensaver.plugin
/usr/lib64/totem/plugins/screenshot/gallery.ui
/usr/lib64/totem/plugins/screenshot/screenshot.plugin
/usr/lib64/totem/plugins/skipto/skipto.plugin
/usr/lib64/totem/plugins/skipto/skipto.ui
/usr/lib64/totem/plugins/variable-rate/variable-rate.plugin
/usr/lib64/totem/plugins/vimeo/vimeo.plugin

%files bin
%defattr(-,root,root,-)
/usr/bin/totem
/usr/bin/totem-video-thumbnailer

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Totem-1.0.typelib
/usr/share/GConf/gsettings/opensubtitles.convert
/usr/share/GConf/gsettings/pythonconsole.convert
/usr/share/GConf/gsettings/totem.convert
/usr/share/applications/org.gnome.Totem.desktop
/usr/share/dbus-1/services/org.gnome.Totem.service
/usr/share/gir-1.0/*.gir
/usr/share/glib-2.0/schemas/org.gnome.totem.enums.xml
/usr/share/glib-2.0/schemas/org.gnome.totem.gschema.xml
/usr/share/glib-2.0/schemas/org.gnome.totem.plugins.opensubtitles.gschema.xml
/usr/share/glib-2.0/schemas/org.gnome.totem.plugins.pythonconsole.gschema.xml
/usr/share/icons/hicolor/scalable/apps/org.gnome.Totem.svg
/usr/share/icons/hicolor/symbolic/apps/org.gnome.Totem-symbolic.svg
/usr/share/metainfo/org.gnome.Totem.appdata.xml
/usr/share/thumbnailers/totem.thumbnailer
/usr/share/totem/controls.ui
/usr/share/totem/playlist.ui
/usr/share/totem/preferences.ui
/usr/share/totem/shortcuts.ui
/usr/share/totem/totem.ui
/usr/share/totem/uri.ui

%files dev
%defattr(-,root,root,-)
/usr/include/totem/1.0/totem-dirs.h
/usr/include/totem/1.0/totem-interface.h
/usr/include/totem/1.0/totem-plugin.h
/usr/include/totem/1.0/totem.h
/usr/lib64/libtotem.so
/usr/lib64/pkgconfig/totem.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/help/C/totem/adjust-speed.page
/usr/share/help/C/totem/channels.page
/usr/share/help/C/totem/figures/dvd-gnome-notification.png
/usr/share/help/C/totem/figures/dvd-nautilus.png
/usr/share/help/C/totem/figures/org.gnome.Totem.svg
/usr/share/help/C/totem/figures/volume-button-slider.png
/usr/share/help/C/totem/file-open.page
/usr/share/help/C/totem/index.page
/usr/share/help/C/totem/navigation.page
/usr/share/help/C/totem/playing-DVD.page
/usr/share/help/C/totem/preferences.page
/usr/share/help/C/totem/properties.page
/usr/share/help/C/totem/screenshot-gallery.page
/usr/share/help/C/totem/screenshot.page
/usr/share/help/C/totem/sound-language.page
/usr/share/help/C/totem/sound-volume.page
/usr/share/help/C/totem/subtitles.page
/usr/share/help/C/totem/supported-formats.page
/usr/share/help/C/totem/troubleshooting-Audio-CD.page
/usr/share/help/C/totem/troubleshooting-DVD.page
/usr/share/help/C/totem/troubleshooting-debug.page
/usr/share/help/C/totem/troubleshooting-subtitles.page
/usr/share/help/C/totem/view-zoom.page
/usr/share/help/bg/totem/adjust-speed.page
/usr/share/help/bg/totem/channels.page
/usr/share/help/bg/totem/figures/dvd-gnome-notification.png
/usr/share/help/bg/totem/figures/dvd-nautilus.png
/usr/share/help/bg/totem/figures/org.gnome.Totem.svg
/usr/share/help/bg/totem/figures/volume-button-slider.png
/usr/share/help/bg/totem/file-open.page
/usr/share/help/bg/totem/index.page
/usr/share/help/bg/totem/navigation.page
/usr/share/help/bg/totem/playing-DVD.page
/usr/share/help/bg/totem/preferences.page
/usr/share/help/bg/totem/properties.page
/usr/share/help/bg/totem/screenshot-gallery.page
/usr/share/help/bg/totem/screenshot.page
/usr/share/help/bg/totem/sound-language.page
/usr/share/help/bg/totem/sound-volume.page
/usr/share/help/bg/totem/subtitles.page
/usr/share/help/bg/totem/supported-formats.page
/usr/share/help/bg/totem/troubleshooting-Audio-CD.page
/usr/share/help/bg/totem/troubleshooting-DVD.page
/usr/share/help/bg/totem/troubleshooting-debug.page
/usr/share/help/bg/totem/troubleshooting-subtitles.page
/usr/share/help/bg/totem/view-zoom.page
/usr/share/help/ca/totem/adjust-speed.page
/usr/share/help/ca/totem/channels.page
/usr/share/help/ca/totem/figures/dvd-gnome-notification.png
/usr/share/help/ca/totem/figures/dvd-nautilus.png
/usr/share/help/ca/totem/figures/org.gnome.Totem.svg
/usr/share/help/ca/totem/figures/volume-button-slider.png
/usr/share/help/ca/totem/file-open.page
/usr/share/help/ca/totem/index.page
/usr/share/help/ca/totem/navigation.page
/usr/share/help/ca/totem/playing-DVD.page
/usr/share/help/ca/totem/preferences.page
/usr/share/help/ca/totem/properties.page
/usr/share/help/ca/totem/screenshot-gallery.page
/usr/share/help/ca/totem/screenshot.page
/usr/share/help/ca/totem/sound-language.page
/usr/share/help/ca/totem/sound-volume.page
/usr/share/help/ca/totem/subtitles.page
/usr/share/help/ca/totem/supported-formats.page
/usr/share/help/ca/totem/troubleshooting-Audio-CD.page
/usr/share/help/ca/totem/troubleshooting-DVD.page
/usr/share/help/ca/totem/troubleshooting-debug.page
/usr/share/help/ca/totem/troubleshooting-subtitles.page
/usr/share/help/ca/totem/view-zoom.page
/usr/share/help/cs/totem/adjust-speed.page
/usr/share/help/cs/totem/channels.page
/usr/share/help/cs/totem/figures/dvd-gnome-notification.png
/usr/share/help/cs/totem/figures/dvd-nautilus.png
/usr/share/help/cs/totem/figures/org.gnome.Totem.svg
/usr/share/help/cs/totem/figures/volume-button-slider.png
/usr/share/help/cs/totem/file-open.page
/usr/share/help/cs/totem/index.page
/usr/share/help/cs/totem/navigation.page
/usr/share/help/cs/totem/playing-DVD.page
/usr/share/help/cs/totem/preferences.page
/usr/share/help/cs/totem/properties.page
/usr/share/help/cs/totem/screenshot-gallery.page
/usr/share/help/cs/totem/screenshot.page
/usr/share/help/cs/totem/sound-language.page
/usr/share/help/cs/totem/sound-volume.page
/usr/share/help/cs/totem/subtitles.page
/usr/share/help/cs/totem/supported-formats.page
/usr/share/help/cs/totem/troubleshooting-Audio-CD.page
/usr/share/help/cs/totem/troubleshooting-DVD.page
/usr/share/help/cs/totem/troubleshooting-debug.page
/usr/share/help/cs/totem/troubleshooting-subtitles.page
/usr/share/help/cs/totem/view-zoom.page
/usr/share/help/da/totem/adjust-speed.page
/usr/share/help/da/totem/channels.page
/usr/share/help/da/totem/figures/dvd-gnome-notification.png
/usr/share/help/da/totem/figures/dvd-nautilus.png
/usr/share/help/da/totem/figures/org.gnome.Totem.svg
/usr/share/help/da/totem/figures/volume-button-slider.png
/usr/share/help/da/totem/file-open.page
/usr/share/help/da/totem/index.page
/usr/share/help/da/totem/navigation.page
/usr/share/help/da/totem/playing-DVD.page
/usr/share/help/da/totem/preferences.page
/usr/share/help/da/totem/properties.page
/usr/share/help/da/totem/screenshot-gallery.page
/usr/share/help/da/totem/screenshot.page
/usr/share/help/da/totem/sound-language.page
/usr/share/help/da/totem/sound-volume.page
/usr/share/help/da/totem/subtitles.page
/usr/share/help/da/totem/supported-formats.page
/usr/share/help/da/totem/troubleshooting-Audio-CD.page
/usr/share/help/da/totem/troubleshooting-DVD.page
/usr/share/help/da/totem/troubleshooting-debug.page
/usr/share/help/da/totem/troubleshooting-subtitles.page
/usr/share/help/da/totem/view-zoom.page
/usr/share/help/de/totem/adjust-speed.page
/usr/share/help/de/totem/channels.page
/usr/share/help/de/totem/figures/dvd-gnome-notification.png
/usr/share/help/de/totem/figures/dvd-nautilus.png
/usr/share/help/de/totem/figures/org.gnome.Totem.svg
/usr/share/help/de/totem/figures/volume-button-slider.png
/usr/share/help/de/totem/file-open.page
/usr/share/help/de/totem/index.page
/usr/share/help/de/totem/navigation.page
/usr/share/help/de/totem/playing-DVD.page
/usr/share/help/de/totem/preferences.page
/usr/share/help/de/totem/properties.page
/usr/share/help/de/totem/screenshot-gallery.page
/usr/share/help/de/totem/screenshot.page
/usr/share/help/de/totem/sound-language.page
/usr/share/help/de/totem/sound-volume.page
/usr/share/help/de/totem/subtitles.page
/usr/share/help/de/totem/supported-formats.page
/usr/share/help/de/totem/troubleshooting-Audio-CD.page
/usr/share/help/de/totem/troubleshooting-DVD.page
/usr/share/help/de/totem/troubleshooting-debug.page
/usr/share/help/de/totem/troubleshooting-subtitles.page
/usr/share/help/de/totem/view-zoom.page
/usr/share/help/el/totem/adjust-speed.page
/usr/share/help/el/totem/channels.page
/usr/share/help/el/totem/figures/dvd-gnome-notification.png
/usr/share/help/el/totem/figures/dvd-nautilus.png
/usr/share/help/el/totem/figures/org.gnome.Totem.svg
/usr/share/help/el/totem/figures/volume-button-slider.png
/usr/share/help/el/totem/file-open.page
/usr/share/help/el/totem/index.page
/usr/share/help/el/totem/navigation.page
/usr/share/help/el/totem/playing-DVD.page
/usr/share/help/el/totem/preferences.page
/usr/share/help/el/totem/properties.page
/usr/share/help/el/totem/screenshot-gallery.page
/usr/share/help/el/totem/screenshot.page
/usr/share/help/el/totem/sound-language.page
/usr/share/help/el/totem/sound-volume.page
/usr/share/help/el/totem/subtitles.page
/usr/share/help/el/totem/supported-formats.page
/usr/share/help/el/totem/troubleshooting-Audio-CD.page
/usr/share/help/el/totem/troubleshooting-DVD.page
/usr/share/help/el/totem/troubleshooting-debug.page
/usr/share/help/el/totem/troubleshooting-subtitles.page
/usr/share/help/el/totem/view-zoom.page
/usr/share/help/en_GB/totem/adjust-speed.page
/usr/share/help/en_GB/totem/channels.page
/usr/share/help/en_GB/totem/figures/dvd-gnome-notification.png
/usr/share/help/en_GB/totem/figures/dvd-nautilus.png
/usr/share/help/en_GB/totem/figures/org.gnome.Totem.svg
/usr/share/help/en_GB/totem/figures/volume-button-slider.png
/usr/share/help/en_GB/totem/file-open.page
/usr/share/help/en_GB/totem/index.page
/usr/share/help/en_GB/totem/navigation.page
/usr/share/help/en_GB/totem/playing-DVD.page
/usr/share/help/en_GB/totem/preferences.page
/usr/share/help/en_GB/totem/properties.page
/usr/share/help/en_GB/totem/screenshot-gallery.page
/usr/share/help/en_GB/totem/screenshot.page
/usr/share/help/en_GB/totem/sound-language.page
/usr/share/help/en_GB/totem/sound-volume.page
/usr/share/help/en_GB/totem/subtitles.page
/usr/share/help/en_GB/totem/supported-formats.page
/usr/share/help/en_GB/totem/troubleshooting-Audio-CD.page
/usr/share/help/en_GB/totem/troubleshooting-DVD.page
/usr/share/help/en_GB/totem/troubleshooting-debug.page
/usr/share/help/en_GB/totem/troubleshooting-subtitles.page
/usr/share/help/en_GB/totem/view-zoom.page
/usr/share/help/es/totem/adjust-speed.page
/usr/share/help/es/totem/channels.page
/usr/share/help/es/totem/figures/dvd-gnome-notification.png
/usr/share/help/es/totem/figures/dvd-nautilus.png
/usr/share/help/es/totem/figures/org.gnome.Totem.svg
/usr/share/help/es/totem/figures/volume-button-slider.png
/usr/share/help/es/totem/file-open.page
/usr/share/help/es/totem/index.page
/usr/share/help/es/totem/navigation.page
/usr/share/help/es/totem/playing-DVD.page
/usr/share/help/es/totem/preferences.page
/usr/share/help/es/totem/properties.page
/usr/share/help/es/totem/screenshot-gallery.page
/usr/share/help/es/totem/screenshot.page
/usr/share/help/es/totem/sound-language.page
/usr/share/help/es/totem/sound-volume.page
/usr/share/help/es/totem/subtitles.page
/usr/share/help/es/totem/supported-formats.page
/usr/share/help/es/totem/troubleshooting-Audio-CD.page
/usr/share/help/es/totem/troubleshooting-DVD.page
/usr/share/help/es/totem/troubleshooting-debug.page
/usr/share/help/es/totem/troubleshooting-subtitles.page
/usr/share/help/es/totem/view-zoom.page
/usr/share/help/eu/totem/adjust-speed.page
/usr/share/help/eu/totem/channels.page
/usr/share/help/eu/totem/figures/dvd-gnome-notification.png
/usr/share/help/eu/totem/figures/dvd-nautilus.png
/usr/share/help/eu/totem/figures/org.gnome.Totem.svg
/usr/share/help/eu/totem/figures/volume-button-slider.png
/usr/share/help/eu/totem/file-open.page
/usr/share/help/eu/totem/index.page
/usr/share/help/eu/totem/navigation.page
/usr/share/help/eu/totem/playing-DVD.page
/usr/share/help/eu/totem/preferences.page
/usr/share/help/eu/totem/properties.page
/usr/share/help/eu/totem/screenshot-gallery.page
/usr/share/help/eu/totem/screenshot.page
/usr/share/help/eu/totem/sound-language.page
/usr/share/help/eu/totem/sound-volume.page
/usr/share/help/eu/totem/subtitles.page
/usr/share/help/eu/totem/supported-formats.page
/usr/share/help/eu/totem/troubleshooting-Audio-CD.page
/usr/share/help/eu/totem/troubleshooting-DVD.page
/usr/share/help/eu/totem/troubleshooting-debug.page
/usr/share/help/eu/totem/troubleshooting-subtitles.page
/usr/share/help/eu/totem/view-zoom.page
/usr/share/help/fi/totem/adjust-speed.page
/usr/share/help/fi/totem/channels.page
/usr/share/help/fi/totem/figures/dvd-gnome-notification.png
/usr/share/help/fi/totem/figures/dvd-nautilus.png
/usr/share/help/fi/totem/figures/org.gnome.Totem.svg
/usr/share/help/fi/totem/figures/volume-button-slider.png
/usr/share/help/fi/totem/file-open.page
/usr/share/help/fi/totem/index.page
/usr/share/help/fi/totem/navigation.page
/usr/share/help/fi/totem/playing-DVD.page
/usr/share/help/fi/totem/preferences.page
/usr/share/help/fi/totem/properties.page
/usr/share/help/fi/totem/screenshot-gallery.page
/usr/share/help/fi/totem/screenshot.page
/usr/share/help/fi/totem/sound-language.page
/usr/share/help/fi/totem/sound-volume.page
/usr/share/help/fi/totem/subtitles.page
/usr/share/help/fi/totem/supported-formats.page
/usr/share/help/fi/totem/troubleshooting-Audio-CD.page
/usr/share/help/fi/totem/troubleshooting-DVD.page
/usr/share/help/fi/totem/troubleshooting-debug.page
/usr/share/help/fi/totem/troubleshooting-subtitles.page
/usr/share/help/fi/totem/view-zoom.page
/usr/share/help/fr/totem/adjust-speed.page
/usr/share/help/fr/totem/channels.page
/usr/share/help/fr/totem/figures/dvd-gnome-notification.png
/usr/share/help/fr/totem/figures/dvd-nautilus.png
/usr/share/help/fr/totem/figures/org.gnome.Totem.svg
/usr/share/help/fr/totem/figures/volume-button-slider.png
/usr/share/help/fr/totem/file-open.page
/usr/share/help/fr/totem/index.page
/usr/share/help/fr/totem/navigation.page
/usr/share/help/fr/totem/playing-DVD.page
/usr/share/help/fr/totem/preferences.page
/usr/share/help/fr/totem/properties.page
/usr/share/help/fr/totem/screenshot-gallery.page
/usr/share/help/fr/totem/screenshot.page
/usr/share/help/fr/totem/sound-language.page
/usr/share/help/fr/totem/sound-volume.page
/usr/share/help/fr/totem/subtitles.page
/usr/share/help/fr/totem/supported-formats.page
/usr/share/help/fr/totem/troubleshooting-Audio-CD.page
/usr/share/help/fr/totem/troubleshooting-DVD.page
/usr/share/help/fr/totem/troubleshooting-debug.page
/usr/share/help/fr/totem/troubleshooting-subtitles.page
/usr/share/help/fr/totem/view-zoom.page
/usr/share/help/gl/totem/adjust-speed.page
/usr/share/help/gl/totem/channels.page
/usr/share/help/gl/totem/figures/dvd-gnome-notification.png
/usr/share/help/gl/totem/figures/dvd-nautilus.png
/usr/share/help/gl/totem/figures/org.gnome.Totem.svg
/usr/share/help/gl/totem/figures/volume-button-slider.png
/usr/share/help/gl/totem/file-open.page
/usr/share/help/gl/totem/index.page
/usr/share/help/gl/totem/navigation.page
/usr/share/help/gl/totem/playing-DVD.page
/usr/share/help/gl/totem/preferences.page
/usr/share/help/gl/totem/properties.page
/usr/share/help/gl/totem/screenshot-gallery.page
/usr/share/help/gl/totem/screenshot.page
/usr/share/help/gl/totem/sound-language.page
/usr/share/help/gl/totem/sound-volume.page
/usr/share/help/gl/totem/subtitles.page
/usr/share/help/gl/totem/supported-formats.page
/usr/share/help/gl/totem/troubleshooting-Audio-CD.page
/usr/share/help/gl/totem/troubleshooting-DVD.page
/usr/share/help/gl/totem/troubleshooting-debug.page
/usr/share/help/gl/totem/troubleshooting-subtitles.page
/usr/share/help/gl/totem/view-zoom.page
/usr/share/help/hr/totem/adjust-speed.page
/usr/share/help/hr/totem/channels.page
/usr/share/help/hr/totem/figures/dvd-gnome-notification.png
/usr/share/help/hr/totem/figures/dvd-nautilus.png
/usr/share/help/hr/totem/figures/org.gnome.Totem.svg
/usr/share/help/hr/totem/figures/volume-button-slider.png
/usr/share/help/hr/totem/file-open.page
/usr/share/help/hr/totem/index.page
/usr/share/help/hr/totem/navigation.page
/usr/share/help/hr/totem/playing-DVD.page
/usr/share/help/hr/totem/preferences.page
/usr/share/help/hr/totem/properties.page
/usr/share/help/hr/totem/screenshot-gallery.page
/usr/share/help/hr/totem/screenshot.page
/usr/share/help/hr/totem/sound-language.page
/usr/share/help/hr/totem/sound-volume.page
/usr/share/help/hr/totem/subtitles.page
/usr/share/help/hr/totem/supported-formats.page
/usr/share/help/hr/totem/troubleshooting-Audio-CD.page
/usr/share/help/hr/totem/troubleshooting-DVD.page
/usr/share/help/hr/totem/troubleshooting-debug.page
/usr/share/help/hr/totem/troubleshooting-subtitles.page
/usr/share/help/hr/totem/view-zoom.page
/usr/share/help/hu/totem/adjust-speed.page
/usr/share/help/hu/totem/channels.page
/usr/share/help/hu/totem/figures/dvd-gnome-notification.png
/usr/share/help/hu/totem/figures/dvd-nautilus.png
/usr/share/help/hu/totem/figures/org.gnome.Totem.svg
/usr/share/help/hu/totem/figures/volume-button-slider.png
/usr/share/help/hu/totem/file-open.page
/usr/share/help/hu/totem/index.page
/usr/share/help/hu/totem/navigation.page
/usr/share/help/hu/totem/playing-DVD.page
/usr/share/help/hu/totem/preferences.page
/usr/share/help/hu/totem/properties.page
/usr/share/help/hu/totem/screenshot-gallery.page
/usr/share/help/hu/totem/screenshot.page
/usr/share/help/hu/totem/sound-language.page
/usr/share/help/hu/totem/sound-volume.page
/usr/share/help/hu/totem/subtitles.page
/usr/share/help/hu/totem/supported-formats.page
/usr/share/help/hu/totem/troubleshooting-Audio-CD.page
/usr/share/help/hu/totem/troubleshooting-DVD.page
/usr/share/help/hu/totem/troubleshooting-debug.page
/usr/share/help/hu/totem/troubleshooting-subtitles.page
/usr/share/help/hu/totem/view-zoom.page
/usr/share/help/id/totem/adjust-speed.page
/usr/share/help/id/totem/channels.page
/usr/share/help/id/totem/figures/dvd-gnome-notification.png
/usr/share/help/id/totem/figures/dvd-nautilus.png
/usr/share/help/id/totem/figures/org.gnome.Totem.svg
/usr/share/help/id/totem/figures/volume-button-slider.png
/usr/share/help/id/totem/file-open.page
/usr/share/help/id/totem/index.page
/usr/share/help/id/totem/navigation.page
/usr/share/help/id/totem/playing-DVD.page
/usr/share/help/id/totem/preferences.page
/usr/share/help/id/totem/properties.page
/usr/share/help/id/totem/screenshot-gallery.page
/usr/share/help/id/totem/screenshot.page
/usr/share/help/id/totem/sound-language.page
/usr/share/help/id/totem/sound-volume.page
/usr/share/help/id/totem/subtitles.page
/usr/share/help/id/totem/supported-formats.page
/usr/share/help/id/totem/troubleshooting-Audio-CD.page
/usr/share/help/id/totem/troubleshooting-DVD.page
/usr/share/help/id/totem/troubleshooting-debug.page
/usr/share/help/id/totem/troubleshooting-subtitles.page
/usr/share/help/id/totem/view-zoom.page
/usr/share/help/it/totem/adjust-speed.page
/usr/share/help/it/totem/channels.page
/usr/share/help/it/totem/figures/dvd-gnome-notification.png
/usr/share/help/it/totem/figures/dvd-nautilus.png
/usr/share/help/it/totem/figures/org.gnome.Totem.svg
/usr/share/help/it/totem/figures/volume-button-slider.png
/usr/share/help/it/totem/file-open.page
/usr/share/help/it/totem/index.page
/usr/share/help/it/totem/navigation.page
/usr/share/help/it/totem/playing-DVD.page
/usr/share/help/it/totem/preferences.page
/usr/share/help/it/totem/properties.page
/usr/share/help/it/totem/screenshot-gallery.page
/usr/share/help/it/totem/screenshot.page
/usr/share/help/it/totem/sound-language.page
/usr/share/help/it/totem/sound-volume.page
/usr/share/help/it/totem/subtitles.page
/usr/share/help/it/totem/supported-formats.page
/usr/share/help/it/totem/troubleshooting-Audio-CD.page
/usr/share/help/it/totem/troubleshooting-DVD.page
/usr/share/help/it/totem/troubleshooting-debug.page
/usr/share/help/it/totem/troubleshooting-subtitles.page
/usr/share/help/it/totem/view-zoom.page
/usr/share/help/ja/totem/adjust-speed.page
/usr/share/help/ja/totem/channels.page
/usr/share/help/ja/totem/figures/dvd-gnome-notification.png
/usr/share/help/ja/totem/figures/dvd-nautilus.png
/usr/share/help/ja/totem/figures/org.gnome.Totem.svg
/usr/share/help/ja/totem/figures/volume-button-slider.png
/usr/share/help/ja/totem/file-open.page
/usr/share/help/ja/totem/index.page
/usr/share/help/ja/totem/navigation.page
/usr/share/help/ja/totem/playing-DVD.page
/usr/share/help/ja/totem/preferences.page
/usr/share/help/ja/totem/properties.page
/usr/share/help/ja/totem/screenshot-gallery.page
/usr/share/help/ja/totem/screenshot.page
/usr/share/help/ja/totem/sound-language.page
/usr/share/help/ja/totem/sound-volume.page
/usr/share/help/ja/totem/subtitles.page
/usr/share/help/ja/totem/supported-formats.page
/usr/share/help/ja/totem/troubleshooting-Audio-CD.page
/usr/share/help/ja/totem/troubleshooting-DVD.page
/usr/share/help/ja/totem/troubleshooting-debug.page
/usr/share/help/ja/totem/troubleshooting-subtitles.page
/usr/share/help/ja/totem/view-zoom.page
/usr/share/help/nb/totem/adjust-speed.page
/usr/share/help/nb/totem/channels.page
/usr/share/help/nb/totem/figures/dvd-gnome-notification.png
/usr/share/help/nb/totem/figures/dvd-nautilus.png
/usr/share/help/nb/totem/figures/org.gnome.Totem.svg
/usr/share/help/nb/totem/figures/volume-button-slider.png
/usr/share/help/nb/totem/file-open.page
/usr/share/help/nb/totem/index.page
/usr/share/help/nb/totem/navigation.page
/usr/share/help/nb/totem/playing-DVD.page
/usr/share/help/nb/totem/preferences.page
/usr/share/help/nb/totem/properties.page
/usr/share/help/nb/totem/screenshot-gallery.page
/usr/share/help/nb/totem/screenshot.page
/usr/share/help/nb/totem/sound-language.page
/usr/share/help/nb/totem/sound-volume.page
/usr/share/help/nb/totem/subtitles.page
/usr/share/help/nb/totem/supported-formats.page
/usr/share/help/nb/totem/troubleshooting-Audio-CD.page
/usr/share/help/nb/totem/troubleshooting-DVD.page
/usr/share/help/nb/totem/troubleshooting-debug.page
/usr/share/help/nb/totem/troubleshooting-subtitles.page
/usr/share/help/nb/totem/view-zoom.page
/usr/share/help/oc/totem/adjust-speed.page
/usr/share/help/oc/totem/channels.page
/usr/share/help/oc/totem/figures/dvd-gnome-notification.png
/usr/share/help/oc/totem/figures/dvd-nautilus.png
/usr/share/help/oc/totem/figures/org.gnome.Totem.svg
/usr/share/help/oc/totem/figures/volume-button-slider.png
/usr/share/help/oc/totem/file-open.page
/usr/share/help/oc/totem/index.page
/usr/share/help/oc/totem/navigation.page
/usr/share/help/oc/totem/playing-DVD.page
/usr/share/help/oc/totem/preferences.page
/usr/share/help/oc/totem/properties.page
/usr/share/help/oc/totem/screenshot-gallery.page
/usr/share/help/oc/totem/screenshot.page
/usr/share/help/oc/totem/sound-language.page
/usr/share/help/oc/totem/sound-volume.page
/usr/share/help/oc/totem/subtitles.page
/usr/share/help/oc/totem/supported-formats.page
/usr/share/help/oc/totem/troubleshooting-Audio-CD.page
/usr/share/help/oc/totem/troubleshooting-DVD.page
/usr/share/help/oc/totem/troubleshooting-debug.page
/usr/share/help/oc/totem/troubleshooting-subtitles.page
/usr/share/help/oc/totem/view-zoom.page
/usr/share/help/pa/totem/adjust-speed.page
/usr/share/help/pa/totem/channels.page
/usr/share/help/pa/totem/figures/dvd-gnome-notification.png
/usr/share/help/pa/totem/figures/dvd-nautilus.png
/usr/share/help/pa/totem/figures/org.gnome.Totem.svg
/usr/share/help/pa/totem/figures/volume-button-slider.png
/usr/share/help/pa/totem/file-open.page
/usr/share/help/pa/totem/index.page
/usr/share/help/pa/totem/navigation.page
/usr/share/help/pa/totem/playing-DVD.page
/usr/share/help/pa/totem/preferences.page
/usr/share/help/pa/totem/properties.page
/usr/share/help/pa/totem/screenshot-gallery.page
/usr/share/help/pa/totem/screenshot.page
/usr/share/help/pa/totem/sound-language.page
/usr/share/help/pa/totem/sound-volume.page
/usr/share/help/pa/totem/subtitles.page
/usr/share/help/pa/totem/supported-formats.page
/usr/share/help/pa/totem/troubleshooting-Audio-CD.page
/usr/share/help/pa/totem/troubleshooting-DVD.page
/usr/share/help/pa/totem/troubleshooting-debug.page
/usr/share/help/pa/totem/troubleshooting-subtitles.page
/usr/share/help/pa/totem/view-zoom.page
/usr/share/help/pl/totem/adjust-speed.page
/usr/share/help/pl/totem/channels.page
/usr/share/help/pl/totem/figures/dvd-gnome-notification.png
/usr/share/help/pl/totem/figures/dvd-nautilus.png
/usr/share/help/pl/totem/figures/org.gnome.Totem.svg
/usr/share/help/pl/totem/figures/volume-button-slider.png
/usr/share/help/pl/totem/file-open.page
/usr/share/help/pl/totem/index.page
/usr/share/help/pl/totem/navigation.page
/usr/share/help/pl/totem/playing-DVD.page
/usr/share/help/pl/totem/preferences.page
/usr/share/help/pl/totem/properties.page
/usr/share/help/pl/totem/screenshot-gallery.page
/usr/share/help/pl/totem/screenshot.page
/usr/share/help/pl/totem/sound-language.page
/usr/share/help/pl/totem/sound-volume.page
/usr/share/help/pl/totem/subtitles.page
/usr/share/help/pl/totem/supported-formats.page
/usr/share/help/pl/totem/troubleshooting-Audio-CD.page
/usr/share/help/pl/totem/troubleshooting-DVD.page
/usr/share/help/pl/totem/troubleshooting-debug.page
/usr/share/help/pl/totem/troubleshooting-subtitles.page
/usr/share/help/pl/totem/view-zoom.page
/usr/share/help/pt_BR/totem/adjust-speed.page
/usr/share/help/pt_BR/totem/channels.page
/usr/share/help/pt_BR/totem/figures/dvd-gnome-notification.png
/usr/share/help/pt_BR/totem/figures/dvd-nautilus.png
/usr/share/help/pt_BR/totem/figures/org.gnome.Totem.svg
/usr/share/help/pt_BR/totem/figures/volume-button-slider.png
/usr/share/help/pt_BR/totem/file-open.page
/usr/share/help/pt_BR/totem/index.page
/usr/share/help/pt_BR/totem/navigation.page
/usr/share/help/pt_BR/totem/playing-DVD.page
/usr/share/help/pt_BR/totem/preferences.page
/usr/share/help/pt_BR/totem/properties.page
/usr/share/help/pt_BR/totem/screenshot-gallery.page
/usr/share/help/pt_BR/totem/screenshot.page
/usr/share/help/pt_BR/totem/sound-language.page
/usr/share/help/pt_BR/totem/sound-volume.page
/usr/share/help/pt_BR/totem/subtitles.page
/usr/share/help/pt_BR/totem/supported-formats.page
/usr/share/help/pt_BR/totem/troubleshooting-Audio-CD.page
/usr/share/help/pt_BR/totem/troubleshooting-DVD.page
/usr/share/help/pt_BR/totem/troubleshooting-debug.page
/usr/share/help/pt_BR/totem/troubleshooting-subtitles.page
/usr/share/help/pt_BR/totem/view-zoom.page
/usr/share/help/ro/totem/adjust-speed.page
/usr/share/help/ro/totem/channels.page
/usr/share/help/ro/totem/figures/dvd-gnome-notification.png
/usr/share/help/ro/totem/figures/dvd-nautilus.png
/usr/share/help/ro/totem/figures/org.gnome.Totem.svg
/usr/share/help/ro/totem/figures/volume-button-slider.png
/usr/share/help/ro/totem/file-open.page
/usr/share/help/ro/totem/index.page
/usr/share/help/ro/totem/navigation.page
/usr/share/help/ro/totem/playing-DVD.page
/usr/share/help/ro/totem/preferences.page
/usr/share/help/ro/totem/properties.page
/usr/share/help/ro/totem/screenshot-gallery.page
/usr/share/help/ro/totem/screenshot.page
/usr/share/help/ro/totem/sound-language.page
/usr/share/help/ro/totem/sound-volume.page
/usr/share/help/ro/totem/subtitles.page
/usr/share/help/ro/totem/supported-formats.page
/usr/share/help/ro/totem/troubleshooting-Audio-CD.page
/usr/share/help/ro/totem/troubleshooting-DVD.page
/usr/share/help/ro/totem/troubleshooting-debug.page
/usr/share/help/ro/totem/troubleshooting-subtitles.page
/usr/share/help/ro/totem/view-zoom.page
/usr/share/help/ru/totem/adjust-speed.page
/usr/share/help/ru/totem/channels.page
/usr/share/help/ru/totem/figures/dvd-gnome-notification.png
/usr/share/help/ru/totem/figures/dvd-nautilus.png
/usr/share/help/ru/totem/figures/org.gnome.Totem.svg
/usr/share/help/ru/totem/figures/volume-button-slider.png
/usr/share/help/ru/totem/file-open.page
/usr/share/help/ru/totem/index.page
/usr/share/help/ru/totem/navigation.page
/usr/share/help/ru/totem/playing-DVD.page
/usr/share/help/ru/totem/preferences.page
/usr/share/help/ru/totem/properties.page
/usr/share/help/ru/totem/screenshot-gallery.page
/usr/share/help/ru/totem/screenshot.page
/usr/share/help/ru/totem/sound-language.page
/usr/share/help/ru/totem/sound-volume.page
/usr/share/help/ru/totem/subtitles.page
/usr/share/help/ru/totem/supported-formats.page
/usr/share/help/ru/totem/troubleshooting-Audio-CD.page
/usr/share/help/ru/totem/troubleshooting-DVD.page
/usr/share/help/ru/totem/troubleshooting-debug.page
/usr/share/help/ru/totem/troubleshooting-subtitles.page
/usr/share/help/ru/totem/view-zoom.page
/usr/share/help/sl/totem/adjust-speed.page
/usr/share/help/sl/totem/channels.page
/usr/share/help/sl/totem/figures/dvd-gnome-notification.png
/usr/share/help/sl/totem/figures/dvd-nautilus.png
/usr/share/help/sl/totem/figures/org.gnome.Totem.svg
/usr/share/help/sl/totem/figures/volume-button-slider.png
/usr/share/help/sl/totem/file-open.page
/usr/share/help/sl/totem/index.page
/usr/share/help/sl/totem/navigation.page
/usr/share/help/sl/totem/playing-DVD.page
/usr/share/help/sl/totem/preferences.page
/usr/share/help/sl/totem/properties.page
/usr/share/help/sl/totem/screenshot-gallery.page
/usr/share/help/sl/totem/screenshot.page
/usr/share/help/sl/totem/sound-language.page
/usr/share/help/sl/totem/sound-volume.page
/usr/share/help/sl/totem/subtitles.page
/usr/share/help/sl/totem/supported-formats.page
/usr/share/help/sl/totem/troubleshooting-Audio-CD.page
/usr/share/help/sl/totem/troubleshooting-DVD.page
/usr/share/help/sl/totem/troubleshooting-debug.page
/usr/share/help/sl/totem/troubleshooting-subtitles.page
/usr/share/help/sl/totem/view-zoom.page
/usr/share/help/sv/totem/adjust-speed.page
/usr/share/help/sv/totem/channels.page
/usr/share/help/sv/totem/figures/dvd-gnome-notification.png
/usr/share/help/sv/totem/figures/dvd-nautilus.png
/usr/share/help/sv/totem/figures/org.gnome.Totem.svg
/usr/share/help/sv/totem/figures/volume-button-slider.png
/usr/share/help/sv/totem/file-open.page
/usr/share/help/sv/totem/index.page
/usr/share/help/sv/totem/navigation.page
/usr/share/help/sv/totem/playing-DVD.page
/usr/share/help/sv/totem/preferences.page
/usr/share/help/sv/totem/properties.page
/usr/share/help/sv/totem/screenshot-gallery.page
/usr/share/help/sv/totem/screenshot.page
/usr/share/help/sv/totem/sound-language.page
/usr/share/help/sv/totem/sound-volume.page
/usr/share/help/sv/totem/subtitles.page
/usr/share/help/sv/totem/supported-formats.page
/usr/share/help/sv/totem/troubleshooting-Audio-CD.page
/usr/share/help/sv/totem/troubleshooting-DVD.page
/usr/share/help/sv/totem/troubleshooting-debug.page
/usr/share/help/sv/totem/troubleshooting-subtitles.page
/usr/share/help/sv/totem/view-zoom.page
/usr/share/help/te/totem/adjust-speed.page
/usr/share/help/te/totem/channels.page
/usr/share/help/te/totem/figures/dvd-gnome-notification.png
/usr/share/help/te/totem/figures/dvd-nautilus.png
/usr/share/help/te/totem/figures/org.gnome.Totem.svg
/usr/share/help/te/totem/figures/volume-button-slider.png
/usr/share/help/te/totem/file-open.page
/usr/share/help/te/totem/index.page
/usr/share/help/te/totem/navigation.page
/usr/share/help/te/totem/playing-DVD.page
/usr/share/help/te/totem/preferences.page
/usr/share/help/te/totem/properties.page
/usr/share/help/te/totem/screenshot-gallery.page
/usr/share/help/te/totem/screenshot.page
/usr/share/help/te/totem/sound-language.page
/usr/share/help/te/totem/sound-volume.page
/usr/share/help/te/totem/subtitles.page
/usr/share/help/te/totem/supported-formats.page
/usr/share/help/te/totem/troubleshooting-Audio-CD.page
/usr/share/help/te/totem/troubleshooting-DVD.page
/usr/share/help/te/totem/troubleshooting-debug.page
/usr/share/help/te/totem/troubleshooting-subtitles.page
/usr/share/help/te/totem/view-zoom.page
/usr/share/help/uk/totem/adjust-speed.page
/usr/share/help/uk/totem/channels.page
/usr/share/help/uk/totem/figures/dvd-gnome-notification.png
/usr/share/help/uk/totem/figures/dvd-nautilus.png
/usr/share/help/uk/totem/figures/org.gnome.Totem.svg
/usr/share/help/uk/totem/figures/volume-button-slider.png
/usr/share/help/uk/totem/file-open.page
/usr/share/help/uk/totem/index.page
/usr/share/help/uk/totem/navigation.page
/usr/share/help/uk/totem/playing-DVD.page
/usr/share/help/uk/totem/preferences.page
/usr/share/help/uk/totem/properties.page
/usr/share/help/uk/totem/screenshot-gallery.page
/usr/share/help/uk/totem/screenshot.page
/usr/share/help/uk/totem/sound-language.page
/usr/share/help/uk/totem/sound-volume.page
/usr/share/help/uk/totem/subtitles.page
/usr/share/help/uk/totem/supported-formats.page
/usr/share/help/uk/totem/troubleshooting-Audio-CD.page
/usr/share/help/uk/totem/troubleshooting-DVD.page
/usr/share/help/uk/totem/troubleshooting-debug.page
/usr/share/help/uk/totem/troubleshooting-subtitles.page
/usr/share/help/uk/totem/view-zoom.page
/usr/share/help/zh_CN/totem/adjust-speed.page
/usr/share/help/zh_CN/totem/channels.page
/usr/share/help/zh_CN/totem/figures/dvd-gnome-notification.png
/usr/share/help/zh_CN/totem/figures/dvd-nautilus.png
/usr/share/help/zh_CN/totem/figures/org.gnome.Totem.svg
/usr/share/help/zh_CN/totem/figures/volume-button-slider.png
/usr/share/help/zh_CN/totem/file-open.page
/usr/share/help/zh_CN/totem/index.page
/usr/share/help/zh_CN/totem/navigation.page
/usr/share/help/zh_CN/totem/playing-DVD.page
/usr/share/help/zh_CN/totem/preferences.page
/usr/share/help/zh_CN/totem/properties.page
/usr/share/help/zh_CN/totem/screenshot-gallery.page
/usr/share/help/zh_CN/totem/screenshot.page
/usr/share/help/zh_CN/totem/sound-language.page
/usr/share/help/zh_CN/totem/sound-volume.page
/usr/share/help/zh_CN/totem/subtitles.page
/usr/share/help/zh_CN/totem/supported-formats.page
/usr/share/help/zh_CN/totem/troubleshooting-Audio-CD.page
/usr/share/help/zh_CN/totem/troubleshooting-DVD.page
/usr/share/help/zh_CN/totem/troubleshooting-debug.page
/usr/share/help/zh_CN/totem/troubleshooting-subtitles.page
/usr/share/help/zh_CN/totem/view-zoom.page
/usr/share/help/zh_HK/totem/adjust-speed.page
/usr/share/help/zh_HK/totem/channels.page
/usr/share/help/zh_HK/totem/figures/dvd-gnome-notification.png
/usr/share/help/zh_HK/totem/figures/dvd-nautilus.png
/usr/share/help/zh_HK/totem/figures/org.gnome.Totem.svg
/usr/share/help/zh_HK/totem/figures/volume-button-slider.png
/usr/share/help/zh_HK/totem/file-open.page
/usr/share/help/zh_HK/totem/index.page
/usr/share/help/zh_HK/totem/navigation.page
/usr/share/help/zh_HK/totem/playing-DVD.page
/usr/share/help/zh_HK/totem/preferences.page
/usr/share/help/zh_HK/totem/properties.page
/usr/share/help/zh_HK/totem/screenshot-gallery.page
/usr/share/help/zh_HK/totem/screenshot.page
/usr/share/help/zh_HK/totem/sound-language.page
/usr/share/help/zh_HK/totem/sound-volume.page
/usr/share/help/zh_HK/totem/subtitles.page
/usr/share/help/zh_HK/totem/supported-formats.page
/usr/share/help/zh_HK/totem/troubleshooting-Audio-CD.page
/usr/share/help/zh_HK/totem/troubleshooting-DVD.page
/usr/share/help/zh_HK/totem/troubleshooting-debug.page
/usr/share/help/zh_HK/totem/troubleshooting-subtitles.page
/usr/share/help/zh_HK/totem/view-zoom.page
/usr/share/help/zh_TW/totem/adjust-speed.page
/usr/share/help/zh_TW/totem/channels.page
/usr/share/help/zh_TW/totem/figures/dvd-gnome-notification.png
/usr/share/help/zh_TW/totem/figures/dvd-nautilus.png
/usr/share/help/zh_TW/totem/figures/org.gnome.Totem.svg
/usr/share/help/zh_TW/totem/figures/volume-button-slider.png
/usr/share/help/zh_TW/totem/file-open.page
/usr/share/help/zh_TW/totem/index.page
/usr/share/help/zh_TW/totem/navigation.page
/usr/share/help/zh_TW/totem/playing-DVD.page
/usr/share/help/zh_TW/totem/preferences.page
/usr/share/help/zh_TW/totem/properties.page
/usr/share/help/zh_TW/totem/screenshot-gallery.page
/usr/share/help/zh_TW/totem/screenshot.page
/usr/share/help/zh_TW/totem/sound-language.page
/usr/share/help/zh_TW/totem/sound-volume.page
/usr/share/help/zh_TW/totem/subtitles.page
/usr/share/help/zh_TW/totem/supported-formats.page
/usr/share/help/zh_TW/totem/troubleshooting-Audio-CD.page
/usr/share/help/zh_TW/totem/troubleshooting-DVD.page
/usr/share/help/zh_TW/totem/troubleshooting-debug.page
/usr/share/help/zh_TW/totem/troubleshooting-subtitles.page
/usr/share/help/zh_TW/totem/view-zoom.page

%files lib
%defattr(-,root,root,-)
/usr/lib64/libtotem.so.0
/usr/lib64/libtotem.so.0.0.0
/usr/lib64/totem/plugins/apple-trailers/libapple-trailers.so
/usr/lib64/totem/plugins/autoload-subtitles/libautoload-subtitles.so
/usr/lib64/totem/plugins/im-status/libtotem-im-status.so
/usr/lib64/totem/plugins/media-player-keys/libmedia-player-keys.so
/usr/lib64/totem/plugins/open-directory/libopen-directory.so
/usr/lib64/totem/plugins/properties/libmovie-properties.so
/usr/lib64/totem/plugins/recent/librecent.so
/usr/lib64/totem/plugins/rotation/librotation.so
/usr/lib64/totem/plugins/save-file/libsave-file.so
/usr/lib64/totem/plugins/screensaver/libscreensaver.so
/usr/lib64/totem/plugins/screenshot/libscreenshot.so
/usr/lib64/totem/plugins/skipto/libskipto.so
/usr/lib64/totem/plugins/variable-rate/libvariable-rate.so
/usr/lib64/totem/plugins/vimeo/libvimeo.so

%files libexec
%defattr(-,root,root,-)
/usr/libexec/totem-gallery-thumbnailer

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/totem/COPYING
/usr/share/package-licenses/totem/license_change

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/totem-video-thumbnailer.1
/usr/share/man/man1/totem.1

%files locales -f totem.lang
%defattr(-,root,root,-)

